Sisham Maharjan

**4. TO DO Task**

Task-1

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

In [ ]:
def convert_units(category, from_unit, to_unit, value):
    """
    Convert between different units of measurement.

    Parameters:
    category (str): The measurement category - 'length', 'weight', or 'volume'
    from_unit (str): The unit to convert from
    to_unit (str): The unit to convert to
    value (float): The numerical value to convert

    Returns:
    float: The converted value
    """
    # Length conversions
    if category == "length":
        if from_unit == "m" and to_unit == "ft":
            return value * 3.281
        elif from_unit == "ft" and to_unit == "m":
            return value / 3.281

    # Weight conversions
    elif category == "weight":
        if from_unit == "kg" and to_unit == "lbs":
            return value * 2.205
        elif from_unit == "lbs" and to_unit == "kg":
            return value / 2.205

    # Volume conversions
    elif category == "volume":
        if from_unit == "L" and to_unit == "gal":
            return value * 0.264172
        elif from_unit == "gal" and to_unit == "L":
            return value / 0.264172

    return None

def get_numeric_input(prompt):
    """
    Get numeric input from user with error handling.

    Parameters:
    prompt (str): The prompt to display to user

    Returns:
    float: The numeric value entered by user
    """
    while True:
        try:
            value = float(input(prompt))
            return value
        except ValueError:
            print("Invalid input! Please enter a number.")

def main():
    """Main program function to run the unit converter."""

    measure = ["Length", "Weight", "Volume"]
    print("📏 Welcome to Unit Converter!")
    print("Please type 1 for Length, 2 for Weight and 3 for Volume")

    try:
        choice = input("Enter your choice (1, 2, or 3): ")

        if choice == "1":  # Length
            print("\n Length Conversion")
            print("Enter 1 to convert meter to feet, or enter 2 to convert feet to meter")
            lg = input("Enter your choice (1, 2): ")

            if lg == "1":
                value = get_numeric_input("Enter the value in meters: ")
                result = convert_units("length", "m", "ft", value)
                print(f"{value} meters = {result:.2f} feet")

            elif lg == "2":
                value = get_numeric_input("Enter the value in feet: ")
                result = convert_units("length", "ft", "m", value)
                print(f"{value} feet = {result:.2f} meters")

            else:
                print(" Please enter 1 or 2")

        elif choice == "2":  # Weight
            print("\nWeight Conversion")
            print("Enter 1 to convert kg to pounds, or enter 2 to convert pounds to kg")
            kg = input("Enter your choice (1, 2): ")

            if kg == "1":
                value = get_numeric_input("Enter the value in kilograms: ")
                result = convert_units("weight", "kg", "lbs", value)
                print(f"{value} kg = {result:.2f} lbs")

            elif kg == "2":
                value = get_numeric_input("Enter the value in pounds: ")
                result = convert_units("weight", "lbs", "kg", value)
                print(f" {value} lbs = {result:.2f} kg")

            else:
                print(" Please enter 1 or 2")

        elif choice == "3":  # Volume
            print("\n Volume Conversion")
            print("Enter 1 to convert liters to gallons, or enter 2 to convert gallons to liters")
            vol = input("Enter your choice (1, 2): ")

            if vol == "1":
                value = get_numeric_input("Enter the value in liters: ")
                result = convert_units("volume", "L", "gal", value)
                print(f" {value} L = {result:.2f} gal")

            elif vol == "2":
                value = get_numeric_input("Enter the value in gallons: ")
                result = convert_units("volume", "gal", "L", value)
                print(f"{value} gal = {result:.2f} L")

            else:
                print("Please enter 1 or 2")

        else:
            print("Invalid choice! Please enter 1, 2, or 3.")

    except Exception as e:
        print(f"An error occurred: {e}")

# to run the program
if __name__ == "__main__":
    main()

📏 Welcome to Unit Converter!
Please type 1 for Length, 2 for Weight and 3 for Volume
Enter your choice (1, 2, or 3): 1

 Length Conversion
Enter 1 to convert meter to feet, or enter 2 to convert feet to meter
Enter your choice (1, 2): 1
Enter the value in meters: 4
4.0 meters = 13.12 feet


Task-2

In [ ]:
def calculate_sum(numbers):
    """
    Calculate the sum of all numbers in a list.

    Parameters:
    numbers (list): A list of numeric values

    Returns:
    float: The sum of all numbers
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculate the average of numbers in a list.

    Parameters:
    numbers (list): A list of numeric values

    Returns:
    float: The average of all numbers

    Raises:
    ValueError: If the list is empty
    """
    if len(numbers) == 0:
        raise ValueError("Cannot calculate average of an empty list")
    return sum(numbers) / len(numbers)

def calculate_maximum(numbers):
    """
    Find the maximum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values

    Returns:
    float: The maximum value in the list

    Raises:
    ValueError: If the list is empty
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find maximum of an empty list")
    return max(numbers)

def calculate_minimum(numbers):
    """
    Find the minimum value in a list of numbers.

    Parameters:
    numbers (list): A list of numeric values

    Returns:
    float: The minimum value in the list

    Raises:
    ValueError: If the list is empty
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find minimum of an empty list")
    return min(numbers)

def get_numbers_from_user():
    """
    Prompt user to enter numbers and convert them to a list of floats.

    Returns:
    list: A list of float numbers entered by the user

    Raises:
    ValueError: If no numbers are entered or input contains non-numeric values
    """
    user_input = input("Enter a list of numbers separated by spaces: ").strip()

    # Check if input is empty
    if not user_input:
        raise ValueError("No numbers entered. Please enter at least one number.")

    # Split the input and convert to float
    try:
        numbers = [float(num) for num in user_input.split()]
    except ValueError:
        raise ValueError("Invalid input! Please enter only numbers separated by spaces.")

    return numbers

def display_menu():
    """Display the operation menu to the user."""
    print("\n" + "="*40)
    print("MATHEMATICAL OPERATIONS MENU")
    print("="*40)
    print("1. Calculate SUM of numbers")
    print("2. Calculate AVERAGE of numbers")
    print("3. Find MAXIMUM value")
    print("4. Find MINIMUM value")
    print("5. Exit")
    print("="*40)

def main():
    """
    Main program function to run the mathematical operations tool.
    """
    print("Welcome to the Mathematical Operations Program!")

    while True:
        # Display menu and get user choice
        display_menu()
        choice = input("Enter your choice (1-5): ").strip()

        # Exit condition
        if choice == "5":
            print("Thank you for using the program. Goodbye!")
            break

        # Validate choice
        if choice not in ["1", "2", "3", "4"]:
            print("Invalid choice! Please enter a number between 1 and 5.")
            continue

        # Get numbers from user
        try:
            numbers = get_numbers_from_user()
            print(f"\nYou entered: {numbers}")
        except ValueError as e:
            print(f"Error: {e}")
            continue

        # Perform selected operation
        if choice == "1":
            result = calculate_sum(numbers)
            print(f"SUM of {numbers} = {result}")

        elif choice == "2":
            try:
                result = calculate_average(numbers)
                print(f"AVERAGE of {numbers} = {result:.2f}")
            except ValueError as e:
                print(f"Error: {e}")

        elif choice == "3":
            try:
                result = calculate_maximum(numbers)
                print(f"MAXIMUM value in {numbers} = {result}")
            except ValueError as e:
                print(f"Error: {e}")

        elif choice == "4":
            try:
                result = calculate_minimum(numbers)
                print(f"MINIMUM value in {numbers} = {result}")
            except ValueError as e:
                print(f"Error: {e}")

        # Ask if user wants to continue
        again = input("\nDo you want to perform another operation? (y/n): ").strip().lower()
        if again != 'y':
            print("Thank you for using the program. Goodbye!")
            break

# Run the program
if __name__ == "__main__":
    main()

Welcome to the Mathematical Operations Program!

MATHEMATICAL OPERATIONS MENU
1. Calculate SUM of numbers
2. Calculate AVERAGE of numbers
3. Find MAXIMUM value
4. Find MINIMUM value
5. Exit
Enter your choice (1-5): 2
Enter a list of numbers separated by spaces: 1 5 2 7 8

You entered: [1.0, 5.0, 2.0, 7.0, 8.0]
AVERAGE of [1.0, 5.0, 2.0, 7.0, 8.0] = 4.60

Do you want to perform another operation? (y/n): y

MATHEMATICAL OPERATIONS MENU
1. Calculate SUM of numbers
2. Calculate AVERAGE of numbers
3. Find MAXIMUM value
4. Find MINIMUM value
5. Exit
Enter your choice (1-5): 3
Enter a list of numbers separated by spaces: 1 5 0 3 2

You entered: [1.0, 5.0, 0.0, 3.0, 2.0]
MAXIMUM value in [1.0, 5.0, 0.0, 3.0, 2.0] = 5.0

Do you want to perform another operation? (y/n): n
Thank you for using the program. Goodbye!


To Do Numpy

In [ ]:
import numpy as np

#Task1: to initialize an empty awway with 2 * 2

array1 = np.empty((2, 2))
print ("Array 1: \n", array1)

#Task2: to initialize all one array with size 4*2
array2 = np.ones((4, 2))
print("\n Array 2: \n", array2)

#Taks 3: return new arra of given shape and type
array3 = np.full((3, 3), 7)
print("\n Array 3: \n", array3)

#Task 4: return new array of ones with same shape and types
array4 = np.ones_like(array3)
print("\n Array 4: \n",array4)

#task 5: Return a new array of zeros with same shape and size
array5 = np.zeros_like(array4)
print("\n Array 5: \n",array5)

#Task 6: existing new_list = [1,2,3,4], convert to numpy array
new_list = [1,2,3,4]
array6 = np.array(new_list)
print("\n Array 6 \n", array6)

Array 1: 
 [[4.04094513e-316 0.00000000e+000]
 [6.55123017e-310 5.78741383e-317]]

 Array 2: 
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

 Array 3: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 Array 4: 
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

 Array 5: 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

 Array 6 
 [1 2 3 4]


Problem 2

In [ ]:
import numpy as np

print("=" * 60)
print("NUMPY ARRAY MANIPULATION TASKS")
print("=" * 60)

# Task 1: Create an array with values ranging from 10 to 49
print("\nTask 1: Array from 10 to 49")
array1 = np.arange(10, 50)
print(array1)
print(f"Shape: {array1.shape}")

# Task 2: Create a 3X3 matrix with values ranging from 0 to 8
print("\nTask 2: 3x3 matrix with values 0 to 8")
array2 = np.arange(9).reshape(3, 3)
print(array2)

# Task 3: Create a 3X3 identity matrix
print("\nTask 3: 3x3 identity matrix")
array3 = np.eye(3)
print(array3)

# Task 4: Create a random array of size 30 and find the mean
print("\nTask 4: Random array of size 30 with mean")
array4 = np.random.random(30)
print(f"Random array: {array4}")
print(f"Mean of array: {array4.mean():.4f}")

# Task 5: Create a 10X10 array with random values and find min and max
print("\nTask 5: 10x10 random array - min and max")
array5 = np.random.random((10, 10))
print(f"Min value: {array5.min():.4f}")
print(f"Max value: {array5.max():.4f}")

# Task 6: Create a zero array of size 10 and replace 5th element with 1
print("\nTask 6: Zero array with 5th element replaced by 1")
array6 = np.zeros(10)
print(f"Original zero array: {array6}")
array6[4] = 1  # 5th element (index 4)
print(f"Modified array: {array6}")

# Task 7: Reverse an array arr = [1,2,0,0,4,0]
print("\nTask 7: Reverse an array")
arr = [1, 2, 0, 0, 4, 0]
array7 = np.array(arr)
print(f"Original array: {array7}")
print(f"Reversed array: {array7[::-1]}")

# Task 8: Create a 2d array with 1 on border and 0 inside
print("\nTask 8: 2D array with 1 on border and 0 inside")
array8 = np.ones((5, 5))
array8[1:-1, 1:-1] = 0
print(array8)

# Task 9: Create an 8X8 matrix and fill it with a checkerboard pattern
print("\nTask 9: 8x8 checkerboard pattern")
array9 = np.zeros((8, 8), dtype=int)
array9[1::2, ::2] = 1  # Fill alternate rows starting from 1 with 1 at even columns
array9[::2, 1::2] = 1  # Fill alternate rows starting from 0 with 1 at odd columns
print(array9)

NUMPY ARRAY MANIPULATION TASKS

Task 1: Array from 10 to 49
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
Shape: (40,)

Task 2: 3x3 matrix with values 0 to 8
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Task 3: 3x3 identity matrix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Task 4: Random array of size 30 with mean
Random array: [0.00102022 0.05470613 0.81782582 0.23712417 0.37331417 0.28432719
 0.84825226 0.90577817 0.51161463 0.55477707 0.38856744 0.39657644
 0.7854527  0.11624086 0.80047237 0.16315608 0.25890761 0.5896943
 0.71397509 0.08379663 0.14664887 0.63139171 0.40836908 0.29594791
 0.46413351 0.51361757 0.78502881 0.16739795 0.9197564  0.79475293]
Mean of array: 0.4671

Task 5: 10x10 random array - min and max
Min value: 0.0034
Max value: 0.9900

Task 6: Zero array with 5th element replaced by 1
Original zero array: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Modified array: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

Task 7: Reverse an array
O

Problem 3

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("=" * 60)
print("NUMPY ARRAY OPERATIONS")
print("=" * 60)

print("\nGiven arrays:")
print(f"x = \n{x}")
print(f"y = \n{y}")
print(f"v = {v}")
print(f"w = {w}")

# Task 1: Add the two arrays
print("\n" + "-" * 40)
print("Task 1: Add x and y")
result1 = x + y
print(f"x + y = \n{result1}")

# Task 2: Subtract the two arrays
print("\n" + "-" * 40)
print("Task 2: Subtract x and y")
result2 = x - y
print(f"x - y = \n{result2}")

# Task 3: Multiply the array with any integers of your choice
print("\n" + "-" * 40)
print("Task 3: Multiply arrays with integers")
result3_x = x * 3
result3_y = y * 5
print(f"x * 3 = \n{result3_x}")
print(f"y * 5 = \n{result3_y}")

# Task 4: Find the square of each element
print("\n" + "-" * 40)
print("Task 4: Square of each element")
result4_x = x ** 2
result4_y = y ** 2
result4_v = v ** 2
print(f"x squared = \n{result4_x}")
print(f"y squared = \n{result4_y}")
print(f"v squared = {result4_v}")

# Task 5: Find dot products
print("\n" + "-" * 40)
print("Task 5: Dot products")

# v and w dot product
dot_vw = np.dot(v, w)
print(f"v · w = {dot_vw}")

# x and v dot product
dot_xv = np.dot(x, v)
print(f"x · v = {dot_xv}")

# x and y dot product
dot_xy = np.dot(x, y)
print(f"x · y = \n{dot_xy}")

# Task 6: Concatenate x and y along row; v and w along column
print("\n" + "-" * 40)
print("Task 6: Concatenation")

# Concatenate x and y along row (vertical stack)
concat_xy_row = np.concatenate((x, y), axis=0)  # or np.vstack((x, y))
print(f"x and y concatenated along row (axis=0):\n{concat_xy_row}")

# Concatenate v and w along column (need to reshape first for column concatenation)
v_reshaped = v.reshape(-1, 1)
w_reshaped = w.reshape(-1, 1)
concat_vw_col = np.concatenate((v_reshaped, w_reshaped), axis=1)
print(f"\nv and w concatenated along column (axis=1):\n{concat_vw_col}")
print(f"v reshaped to column:\n{v_reshaped}")
print(f"w reshaped to column:\n{w_reshaped}")

# Alternative for v and w along column using column_stack
concat_vw_col_alt = np.column_stack((v, w))
print(f"\nAlternative using column_stack:\n{concat_vw_col_alt}")

# Task 7: Concatenate x and v (will cause error)
print("\n" + "-" * 40)
print("Task 7: Attempt to concatenate x and v")
print("x shape:", x.shape)
print("v shape:", v.shape)

try:
    concat_xv = np.concatenate((x, v))
    print(f"x and v concatenated:\n{concat_xv}")
except Exception as e:
    print(f"ERROR: {e}")
    print("\nExplanation:")
    print("x has shape (2, 2) - a 2D array with 2 rows and 2 columns")
    print("v has shape (2,) - a 1D array with 2 elements")
    print("To concatenate, arrays must have the same number of dimensions")
    print("and compatible shapes along the concatenation axis.")
    print("\nSolutions to fix this:")
    print("1. Reshape v to match x's dimensions: v.reshape(2, 1) or v.reshape(1, 2)")
    print("2. Use np.vstack((x, v)) - but v would need to be reshaped to (1, 2)")
    print("3. Flatten x to 1D: x.flatten() and then concatenate with v")

    # Show possible solutions
    print("\nPossible ways to concatenate:")
    # Solution 1: Reshape v to 2D column vector
    v_col = v.reshape(2, 1)
    print(f"v reshaped to (2,1):\n{v_col}")
    print(f"Cannot concatenate with x (2,2) along axis=1 due to shape mismatch")

    # Solution 2: Reshape v to 2D row vector
    v_row = v.reshape(1, 2)
    concat_x_vrow = np.concatenate((x, v_row), axis=0)
    print(f"\nv reshaped to (1,2):\n{v_row}")
    print(f"x and v_row concatenated along axis=0:\n{concat_x_vrow}")

    # Solution 3: Flatten x
    x_flat = x.flatten()
    concat_flat = np.concatenate((x_flat, v))
    print(f"\nx flattened: {x_flat}")
    print(f"x_flat and v concatenated: {concat_flat}")

NUMPY ARRAY OPERATIONS

Given arrays:
x = 
[[1 2]
 [3 5]]
y = 
[[5 6]
 [7 8]]
v = [ 9 10]
w = [11 12]

----------------------------------------
Task 1: Add x and y
x + y = 
[[ 6  8]
 [10 13]]

----------------------------------------
Task 2: Subtract x and y
x - y = 
[[-4 -4]
 [-4 -3]]

----------------------------------------
Task 3: Multiply arrays with integers
x * 3 = 
[[ 3  6]
 [ 9 15]]
y * 5 = 
[[25 30]
 [35 40]]

----------------------------------------
Task 4: Square of each element
x squared = 
[[ 1  4]
 [ 9 25]]
y squared = 
[[25 36]
 [49 64]]
v squared = [ 81 100]

----------------------------------------
Task 5: Dot products
v · w = 219
x · v = [29 77]
x · y = 
[[19 22]
 [50 58]]

----------------------------------------
Task 6: Concatenation
x and y concatenated along row (axis=0):
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

v and w concatenated along column (axis=1):
[[ 9 11]
 [10 12]]
v reshaped to column:
[[ 9]
 [10]]
w reshaped to column:
[[11]
 [12]]

Alternative using column_stack

Problem 4

In [ ]:
import numpy as np

# Given arrays
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("=" * 60)
print("MATRIX OPERATIONS AND LINEAR SYSTEMS")
print("=" * 60)

print("\nGiven matrices:")
print(f"A = \n{A}")
print(f"B = \n{B}")

# Task 1: Prove A.A^(-1) = I
print("\n" + "-" * 60)
print("Task 1: Prove A · A⁻¹ = I")

# Calculate inverse of A
A_inv = np.linalg.inv(A)
print(f"A⁻¹ = \n{A_inv}")

# Multiply A with its inverse
result = np.dot(A, A_inv)
print(f"\nA · A⁻¹ = \n{result}")

# Check if it's identity (within floating point precision)
identity = np.eye(2)
is_identity = np.allclose(result, identity)
print(f"\nIs A · A⁻¹ equal to identity matrix? {is_identity}")

if is_identity:
    print("✓ Proven: A · A⁻¹ = I")

# Task 2: Prove AB ≠ BA
print("\n" + "-" * 60)
print("Task 2: Prove AB ≠ BA")

# Calculate AB
AB = np.dot(A, B)
print(f"AB = \n{AB}")

# Calculate BA
BA = np.dot(B, A)
print(f"BA = \n{BA}")

# Check if they are equal
are_equal = np.array_equal(AB, BA)
print(f"\nIs AB equal to BA? {are_equal}")

if not are_equal:
    print("✓ Proven: AB ≠ BA")

# Task 3: Prove (AB)^T = B^T A^T
print("\n" + "-" * 60)
print("Task 3: Prove (AB)ᵀ = Bᵀ Aᵀ")

# Calculate (AB)^T
AB_transpose = np.transpose(AB)
print(f"(AB)ᵀ = \n{AB_transpose}")

# Calculate B^T A^T
B_transpose = np.transpose(B)
A_transpose = np.transpose(A)
BT_AT = np.dot(B_transpose, A_transpose)
print(f"Bᵀ Aᵀ = \n{BT_AT}")

# Check if they are equal
are_equal_transpose = np.allclose(AB_transpose, BT_AT)
print(f"\nIs (AB)ᵀ equal to Bᵀ Aᵀ? {are_equal_transpose}")

if are_equal_transpose:
    print("✓ Proven: (AB)ᵀ = Bᵀ Aᵀ")

# Task 4: Solve system of linear equations using Inverse Method
print("\n" + "-" * 60)
print("Task 4: Solve Linear System using Inverse Method")
print("2x - 3y + z = -1")
print("x - y + 2z = -3")
print("3x + y - z = 9")

# Represent the system in matrix form: AX = B
# Where A is coefficient matrix, X is variable matrix, B is constant matrix
A_system = np.array([[2, -3, 1],
                     [1, -1, 2],
                     [3, 1, -1]])

B_system = np.array([-1, -3, 9])

print(f"\nCoefficient matrix A = \n{A_system}")
print(f"Constant matrix B = {B_system}")

# Method 1: Using inverse method
print("\n" + "-" * 30)
print("Method 1: Using A⁻¹ B")

# Calculate inverse of A_system
A_system_inv = np.linalg.inv(A_system)
print(f"A⁻¹ = \n{A_system_inv}")

# Solve for X = A⁻¹ B
X_solution = np.dot(A_system_inv, B_system)
print(f"\nSolution X = A⁻¹ B = {X_solution}")

# Method 2: Using np.linalg.solve (more efficient)
print("\n" + "-" * 30)
print("Method 2: Using np.linalg.solve()")
X_solution_2 = np.linalg.solve(A_system, B_system)
print(f"Solution using solve(): {X_solution_2}")

# Method 3: Using np.linalg.inv directly
print("\n" + "-" * 30)
print("Method 3: Using np.linalg.inv directly")
X_solution_3 = np.linalg.inv(A_system).dot(B_system)
print(f"Solution using inv().dot(): {X_solution_3}")

# Verify the solution
print("\n" + "-" * 30)
print("Verification:")
x, y, z = X_solution
print(f"x = {x:.2f}, y = {y:.2f}, z = {z:.2f}")

# Check each equation
eq1 = 2*x - 3*y + z
eq2 = x - y + 2*z
eq3 = 3*x + y - z

print(f"\nEquation 1: 2({x:.2f}) - 3({y:.2f}) + ({z:.2f}) = {eq1:.2f} (should be -1)")
print(f"Equation 2: ({x:.2f}) - ({y:.2f}) + 2({z:.2f}) = {eq2:.2f} (should be -3)")
print(f"Equation 3: 3({x:.2f}) + ({y:.2f}) - ({z:.2f}) = {eq3:.2f} (should be 9)")

# Check if solution satisfies all equations
verification = np.allclose(np.dot(A_system, X_solution), B_system)
print(f"\nDoes the solution satisfy all equations? {verification}")

# Additional linalg functions exploration
print("\n" + "-" * 60)
print("EXPLORING NUMPY.LINALG FUNCTIONS")
print("-" * 60)

print("\n1. Matrix Determinant:")
det_A = np.linalg.det(A_system)
print(f"   det(A) = {det_A:.2f}")

print("\n2. Matrix Rank:")
rank_A = np.linalg.matrix_rank(A_system)
print(f"   rank(A) = {rank_A}")

print("\n3. Matrix Condition Number:")
cond_A = np.linalg.cond(A_system)
print(f"   cond(A) = {cond_A:.2f}")

print("\n4. Eigenvalues and Eigenvectors:")
eigenvalues, eigenvectors = np.linalg.eig(A_system)
print(f"   Eigenvalues: {eigenvalues}")
print(f"   Eigenvectors:\n{eigenvectors}")

print("\n5. Norm of matrices:")
norm_A = np.linalg.norm(A_system)
print(f"   Norm of A: {norm_A:.2f}")
norm_B = np.linalg.norm(B_system)
print(f"   Norm of B: {norm_B:.2f}")

MATRIX OPERATIONS AND LINEAR SYSTEMS

Given matrices:
A = 
[[3 4]
 [7 8]]
B = 
[[5 3]
 [2 1]]

------------------------------------------------------------
Task 1: Prove A · A⁻¹ = I
A⁻¹ = 
[[-2.    1.  ]
 [ 1.75 -0.75]]

A · A⁻¹ = 
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is A · A⁻¹ equal to identity matrix? True
✓ Proven: A · A⁻¹ = I

------------------------------------------------------------
Task 2: Prove AB ≠ BA
AB = 
[[23 13]
 [51 29]]
BA = 
[[36 44]
 [13 16]]

Is AB equal to BA? False
✓ Proven: AB ≠ BA

------------------------------------------------------------
Task 3: Prove (AB)ᵀ = Bᵀ Aᵀ
(AB)ᵀ = 
[[23 51]
 [13 29]]
Bᵀ Aᵀ = 
[[23 51]
 [13 29]]

Is (AB)ᵀ equal to Bᵀ Aᵀ? True
✓ Proven: (AB)ᵀ = Bᵀ Aᵀ

------------------------------------------------------------
Task 4: Solve Linear System using Inverse Method
2x - 3y + z = -1
x - y + 2z = -3
3x + y - z = 9

Coefficient matrix A = 
[[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Constant matrix B = [-1 -3  9]

----

4.2 List Manipulation

In [ ]:
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Args:
        lst (list): The input list.

    Returns:
        list: A new list containing every other element.
    """
    return lst[::2]

# Example usage:
input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)
print(f"Original list: {input_list}")
print(f"Every other element: {output_list}")

input_list_2 = ['a', 'b', 'c', 'd', 'e']
output_list_2 = extract_every_other(input_list_2)
print(f"\nOriginal list: {input_list_2}")
print(f"Every other element: {output_list_2}")

Original list: [1, 2, 3, 4, 5, 6]
Every other element: [1, 3, 5]

Original list: ['a', 'b', 'c', 'd', 'e']
Every other element: ['a', 'c', 'e']


In [ ]:
def get_sublist(lst, start, end):
    """
    Returns a sublist from a given list starting at index 'start'
    and ending at index 'end' (inclusive).

    Args:
        lst (list): The input list
        start (int): Starting index
        end (int): Ending index

    Returns:
        list: Sublist from start to end
    """
    return lst[start:end+1]


# Example usage
input_list = [1, 2, 3, 4, 5, 6]
result = get_sublist(input_list, 2, 4)

print("Original list:", input_list)
print("Sublist from index 2 to 4:", result)

Original list: [1, 2, 3, 4, 5, 6]
Sublist from index 2 to 4: [3, 4, 5]


In [ ]:
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Args:
        lst (list): The input list

    Returns:
        list: Reversed list
    """
    return lst[::-1]


# Example usage
input_list = [1, 2, 3, 4, 5]
reversed_list = reverse_list(input_list)

print("Original list:", input_list)
print("Reversed list:", reversed_list)

Original list: [1, 2, 3, 4, 5]
Reversed list: [5, 4, 3, 2, 1]


In [ ]:
def remove_first_last(lst):
    """
    Removes the first and last elements of a list using slicing.

    Args:
        lst (list): The input list

    Returns:
        list: A list without the first and last elements
    """
    return lst[1:-1]


# Example usage
input_list = [1, 2, 3, 4, 5]
result = remove_first_last(input_list)

print("Original list:", input_list)
print("List without first and last elements:", result)

Original list: [1, 2, 3, 4, 5]
List without first and last elements: [2, 3, 4]


In [ ]:
def get_first_n(lst, n):
    """
    Returns the first n elements from a list using slicing.

    Args:
        lst (list): The input list
        n (int): Number of elements to extract

    Returns:
        list: First n elements of the list
    """
    return lst[:n]


# Example usage
input_list = [1, 2, 3, 4, 5]
result = get_first_n(input_list, 3)

print("Original list:", input_list)
print("First 3 elements:", result)

Original list: [1, 2, 3, 4, 5]
First 3 elements: [1, 2, 3]


In [ ]:
def get_last_n(lst, n):
    """
    Returns the last n elements from a list using slicing.

    Args:
        lst (list): The input list
        n (int): Number of elements to extract from the end

    Returns:
        list: Last n elements of the list
    """
    return lst[-n:]


# Example usage
input_list = [1, 2, 3, 4, 5]
result = get_last_n(input_list, 2)

print("Original list:", input_list)
print("Last 2 elements:", result)

Original list: [1, 2, 3, 4, 5]
Last 2 elements: [4, 5]


4.2 Excercise on Nested List

In [ ]:
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Args:
        lst (list): A nested list

    Returns:
        list: A flattened list
    """
    flat_list = []
    for sublist in lst:
        flat_list.extend(sublist)
    return flat_list


# Example usage
input_list = [[1, 2], [3, 4], [5]]
result = flatten(input_list)

print("Original nested list:", input_list)
print("Flattened list:", result)

Original nested list: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


In [ ]:
def access_nested_element(lst, indices):
    """
    Returns a specific element from a nested list using given indices.

    Args:
        lst (list): The nested list
        indices (list): List of indices to access the element

    Returns:
        element: The element at the specified position
    """
    element = lst
    for i in indices:
        element = element[i]
    return element


# Example usage
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]

result = access_nested_element(lst, indices)

print("Nested list:", lst)
print("Element at indices", indices, ":", result)

Nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Element at indices [1, 2] : 6


In [ ]:
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list.

    Args:
        lst (list): A nested list containing numbers

    Returns:
        int/float: Sum of all elements
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # recursive call
        else:
            total += item
    return total


# Example usage
input_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(input_list)

print("Nested list:", input_list)
print("Sum of all elements:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


In [ ]:
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Args:
        lst (list): Nested list
        elem: Element to remove

    Returns:
        list: Modified nested list
    """
    result = []

    for sublist in lst:
        new_sublist = []
        for item in sublist:
            if item != elem:
                new_sublist.append(item)
        result.append(new_sublist)

    return result


# Example usage
lst = [[1, 2], [3, 2], [4, 5]]
elem = 2

result = remove_element(lst, elem)

print("Original list:", lst)
print("List after removing element:", result)

Original list: [[1, 2], [3, 2], [4, 5]]
List after removing element: [[1], [3], [4, 5]]


In [ ]:
def find_max(lst):
    """
    Finds the maximum element in a nested list of any depth.

    Args:
        lst (list): A nested list containing numbers

    Returns:
        int/float: Maximum element
    """
    maximum = float('-inf')  # start with negative infinity

    for item in lst:
        if isinstance(item, list):
            # Recursively find the max in the sublist
            sub_max = find_max(item)
            if sub_max > maximum:
                maximum = sub_max
        else:
            if item > maximum:
                maximum = item

    return maximum


# Example usage
nested_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested_list)

print("Nested list:", nested_list)
print("Maximum element:", result)

Nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6


In [ ]:
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Args:
        lst (list): Nested list
        elem: Element to count

    Returns:
        int: Number of occurrences
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            # Recursively count in the sublist
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count


# Example usage
lst = [[1, 2], [2, 3], [2, 4]]
elem = 2

result = count_occurrences(lst, elem)

print("Nested list:", lst)
print(f"Occurrences of {elem}:", result)

Nested list: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


In [ ]:
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    Args:
        lst (list): Deeply nested list

    Returns:
        list: Flattened list
    """
    flat_list = []
    for item in lst:
        if isinstance(item, list):
            # Recursively flatten the sublist
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)
    return flat_list


# Example usage
nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)

print("Original nested list:", nested_list)
print("Flattened list:", result)

Original nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


In [ ]:
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Args:
        lst (list): Nested list

    Returns:
        float: Average of all elements
    """
    def flatten(lst):
        """Helper function to flatten nested lists"""
        flat_list = []
        for item in lst:
            if isinstance(item, list):
                flat_list.extend(flatten(item))
            else:
                flat_list.append(item)
        return flat_list

    flat_list = flatten(lst)
    total = sum(flat_list)
    count = len(flat_list)
    return total / count if count != 0 else 0


# Example usage
nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)

print("Nested list:", nested_list)
print("Average of all elements:", result)

Nested list: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5
